spring:
  application:
    name: ws-seguros-complementario

  datasource:
    url: "${DB_URL:jdbc:oracle:thin:@//localhost:1521/ORCLPDB}"
    username: "${DB_USERNAME:VIDA_APP}"
    password: "${DB_PASSWORD:}"
    driver-class-name: oracle.jdbc.OracleDriver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 80

integraciones:
  sftp:
    upload-url: "${SFTP_UPLOAD_URL:https://appsqa.essalud.gob.pe/sagw/mia-seguros-hijomenormayor/api/sftp/upload}"

  otp:
    generar-url: "${OTP_GENERAR_URL:https://appsqa.essalud.gob.pe/sagw/mia-seguros-hijomenormayor/api/seguro-complementario/genera-otp}"
    validar-url: "${OTP_VALIDAR_URL:https://appsqa.essalud.gob.pe/sagw/mia-seguros-hijomenormayor/api/seguro-complementario/validar-otp}"
    email-url: "${OTP_EMAIL_URL:https://appsqa.essalud.gob.pe/sagw/viva-essalud/viva-apinotificaciones/seguros-complementarios/send-otp-email}"
    token: "${OTP_TOKEN:}"