package essalud.gob.pe.wsseguroscomplementario.common.constants;

public final class EstadoProcesoConstants {

    private EstadoProcesoConstants() {
    }

    public static final String ZONA_HORARIA_LIMA = "America/Lima";

    public static final String CANAL_SOMOS_ESSALUD = "SOMOS_ESSALUD";
    public static final String CANAL_MODULO_AFILIACION_DIGITAL = "MODULO_AFILIACION_DIGITAL";

    public static final String USUARIO_SISTEMA = "SISTEMA";

    public static final String TIPO_DOCUMENTO_TRABAJADOR_DNI = "01";

    public static final String SIN_EXPEDIENTE = "SIN_EXPEDIENTE";

    public static final String PROCESO_INICIADO = "PROCESO_INICIADO";

    public static final String DOCUMENTO_GENERADO = "DOCUMENTO_GENERADO";
    public static final String DOCUMENTOS_GENERADOS = "DOCUMENTOS_GENERADOS";
    public static final String DOCUMENTO_CARGADO = "DOCUMENTO_CARGADO";

    public static final String VALIDACION_DOCUMENTAL_EN_PROCESO = "VALIDACION_DOCUMENTAL_EN_PROCESO";
    public static final String VALIDACION_DOCUMENTAL_APROBADA = "VALIDACION_DOCUMENTAL_APROBADA";
    public static final String RECHAZADO_VALIDACION_DOCUMENTAL = "RECHAZADO_VALIDACION_DOCUMENTAL";

    public static final String DOCUMENTO_SELLADO = "DOCUMENTO_SELLADO";
    public static final String SELLO_ESSALUD_VALIDADO = "SELLO_ESSALUD_VALIDADO";
    public static final String DOCUMENTO_PUBLICADO = "DOCUMENTO_PUBLICADO";

    public static final String OBSERVADO_OPERATIVO = "OBSERVADO_OPERATIVO";
    public static final String REINTENTO_INTERNO_REGISTRADO = "REINTENTO_INTERNO_REGISTRADO";
    public static final String SUBSANADO_OPERATIVAMENTE = "SUBSANADO_OPERATIVAMENTE";

    public static final String ERROR_CIERRE_DOCUMENTAL = "ERROR_CIERRE_DOCUMENTAL";
    public static final String ERROR_PUBLICACION_POR_SELLO_NO_VALIDADO = "ERROR_PUBLICACION_POR_SELLO_NO_VALIDADO";

    public static final String PREFIJO_RECHAZADO = "RECHAZADO";

    public static final String ACCION_INICIAR_PROCESO = "INICIAR_PROCESO";
    public static final String ACCION_COMPLETAR_DATOS_AFILIACION = "COMPLETAR_DATOS_AFILIACION";
    public static final String ACCION_CARGAR_DOCUMENTOS_FIRMADOS = "CARGAR_DOCUMENTOS_FIRMADOS";
    public static final String ACCION_CARGAR_NUEVAMENTE_DOCUMENTO = "CARGAR_NUEVAMENTE_DOCUMENTO";
    public static final String ACCION_ESPERAR_VALIDACION_DOCUMENTAL = "ESPERAR_VALIDACION_DOCUMENTAL";
    public static final String ACCION_ESPERAR_SUBSANACION_INTERNA = "ESPERAR_SUBSANACION_INTERNA";
    public static final String ACCION_ESPERAR_SELLADO_PUBLICACION = "ESPERAR_SELLADO_PUBLICACION";
    public static final String ACCION_CONSULTAR_DOCUMENTOS_PUBLICADOS = "CONSULTAR_DOCUMENTOS_PUBLICADOS";

    public static final String FRONTEND_MOSTRAR_INICIO_AFILIACION = "MOSTRAR_INICIO_AFILIACION";
    public static final String FRONTEND_MOSTRAR_FORMULARIO_AFILIACION = "MOSTRAR_FORMULARIO_AFILIACION";
    public static final String FRONTEND_MOSTRAR_DESCARGA_Y_CARGA_DOCUMENTOS = "MOSTRAR_DESCARGA_Y_CARGA_DOCUMENTOS";
    public static final String FRONTEND_MOSTRAR_CARGA_DOCUMENTO_CORREGIDO = "MOSTRAR_CARGA_DOCUMENTO_CORREGIDO";
    public static final String FRONTEND_MOSTRAR_MENSAJE_VALIDACION_EN_PROCESO = "MOSTRAR_MENSAJE_VALIDACION_EN_PROCESO";
    public static final String FRONTEND_MOSTRAR_MENSAJE_ATENCION_INTERNA = "MOSTRAR_MENSAJE_ATENCION_INTERNA";
    public static final String FRONTEND_MOSTRAR_MENSAJE_PUBLICACION_PENDIENTE = "MOSTRAR_MENSAJE_PUBLICACION_PENDIENTE";
    public static final String FRONTEND_MOSTRAR_DOCUMENTOS_PUBLICADOS = "MOSTRAR_DOCUMENTOS_PUBLICADOS";
}